/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: dirk@opensg.org, gerrit.voss@vossg.org, carsten_neumann@gmx.net  *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class GLFWWindow!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

#include <cstdlib>
#include <cstdio>

#ifdef WIN32 
#pragma warning(disable: 4355) // turn off 'this' : used in base member initializer list warning
#pragma warning(disable: 4290) // disable exception specification warning
#endif

#include "OSGConfig.h"




#include "OSGGLFWWindowBase.h"
#include "OSGGLFWWindow.h"

#include <boost/bind/bind.hpp>

OSG_BEGIN_NAMESPACE

/***************************************************************************\
 *                            Description                                  *
\***************************************************************************/

/*! \class OSG::GLFWWindow
    The class for GLFW-based windows. See \ref PageWindowGLFW for a description.
 */

/***************************************************************************\
 *                        Field Documentation                              *
\***************************************************************************/

/*! \var GLFWwindowP     GLFWWindowBase::_sfGlfwWindow
    
*/


/***************************************************************************\
 *                      FieldType/FieldTrait Instantiation                 *
\***************************************************************************/

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
PointerType FieldTraits<GLFWWindow *, nsOSG>::_type(
    "GLFWWindowPtr", 
    "WindowPtr", 
    GLFWWindow::getClassType(),
    nsOSG);
#endif

OSG_FIELDTRAITS_GETTYPE_NS(GLFWWindow *, nsOSG)

OSG_EXPORT_PTR_SFIELD_FULL(PointerSField,
                           GLFWWindow *,
                           nsOSG)

OSG_EXPORT_PTR_MFIELD_FULL(PointerMField,
                           GLFWWindow *,
                           nsOSG)

/***************************************************************************\
 *                         Field Description                               *
\***************************************************************************/

void GLFWWindowBase::classDescInserter(TypeObject &oType)
{
    FieldDescriptionBase *pDesc = NULL;


    pDesc = new SFGLFWwindowP::Description(
        SFGLFWwindowP::getClassType(),
        "glfwWindow",
        "",
        GlfwWindowFieldId, GlfwWindowFieldMask,
        true,
        (Field::FClusterLocal),
        static_cast<FieldEditMethodSig>(&GLFWWindow::editHandleGlfwWindow),
        static_cast<FieldGetMethodSig >(&GLFWWindow::getHandleGlfwWindow));

    oType.addInitialDesc(pDesc);
}


GLFWWindowBase::TypeObject GLFWWindowBase::_type(
    GLFWWindowBase::getClassname(),
    Inherited::getClassname(),
    "NULL",
    nsOSG, //Namespace
    reinterpret_cast<PrototypeCreateF>(&GLFWWindowBase::createEmptyLocal),
    reinterpret_cast<InitContainerF>(&GLFWWindow::initMethod),
    reinterpret_cast<ExitContainerF>(&GLFWWindow::exitMethod),
    reinterpret_cast<InitalInsertDescFunc>(
        reinterpret_cast<void *>(&GLFWWindow::classDescInserter)),
    false,
    0,
    "<?xml version=\"1.0\"?>\n"
    "\n"
    "<FieldContainer\n"
    "    name=\"GLFWWindow\"\n"
    "    parent=\"NativeWindow\"\n"
    "    library=\"WindowGLFW\"\n"
    "    pointerfieldtypes=\"both\"\n"
    "    structure=\"concrete\"\n"
    "    systemcomponent=\"true\"\n"
    "    parentsystemcomponent=\"true\"\n"
    "    realparent=\"Window\"\n"
    "    docGroupBase=\"GrpWindowGLFW\"\n"
    "    >\n"
    "    The class for GLFW-based windows. See \\ref PageWindowGLFW for a description.\n"
    "    <Field\n"
    "        name=\"glfwWindow\"\n"
    "        type=\"GLFWwindowP\"\n"
    "        cardinality=\"single\"\n"
    "        visibility=\"internal\"\n"
    "        defaultValue=\"nullptr\"\n"
    "        fieldHeader=\"OSGGLFWWindowDataFields.h\"\n"
    "        access=\"public\"\n"
    "        fieldFlags=\"FClusterLocal\"\n"
    "        >\n"
    "    </Field>\n"
    "</FieldContainer>\n",
    "The class for GLFW-based windows. See \\ref PageWindowGLFW for a description.\n"
    );

/*------------------------------ get -----------------------------------*/

FieldContainerType &GLFWWindowBase::getType(void)
{
    return _type;
}

const FieldContainerType &GLFWWindowBase::getType(void) const
{
    return _type;
}

UInt32 GLFWWindowBase::getContainerSize(void) const
{
    return sizeof(GLFWWindow);
}

/*------------------------- decorator get ------------------------------*/


SFGLFWwindowP *GLFWWindowBase::editSFGlfwWindow(void)
{
    editSField(GlfwWindowFieldMask);

    return &_sfGlfwWindow;
}

const SFGLFWwindowP *GLFWWindowBase::getSFGlfwWindow(void) const
{
    return &_sfGlfwWindow;
}






/*------------------------------ access -----------------------------------*/

SizeT GLFWWindowBase::getBinSize(ConstFieldMaskArg whichField)
{
    SizeT returnValue = Inherited::getBinSize(whichField);

    if(FieldBits::NoField != (GlfwWindowFieldMask & whichField))
    {
        returnValue += _sfGlfwWindow.getBinSize();
    }

    return returnValue;
}

void GLFWWindowBase::copyToBin(BinaryDataHandler &pMem,
                                  ConstFieldMaskArg  whichField)
{
    Inherited::copyToBin(pMem, whichField);

    if(FieldBits::NoField != (GlfwWindowFieldMask & whichField))
    {
        _sfGlfwWindow.copyToBin(pMem);
    }
}

void GLFWWindowBase::copyFromBin(BinaryDataHandler &pMem,
                                    ConstFieldMaskArg  whichField)
{
    Inherited::copyFromBin(pMem, whichField);

    if(FieldBits::NoField != (GlfwWindowFieldMask & whichField))
    {
        editSField(GlfwWindowFieldMask);
        _sfGlfwWindow.copyFromBin(pMem);
    }
}

//! create a new instance of the class
GLFWWindowTransitPtr GLFWWindowBase::createLocal(BitVector bFlags)
{
    GLFWWindowTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyLocal(bFlags);

        fc = dynamic_pointer_cast<GLFWWindow>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class, copy the container flags
GLFWWindowTransitPtr GLFWWindowBase::createDependent(BitVector bFlags)
{
    GLFWWindowTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyDependent(bFlags);

        fc = dynamic_pointer_cast<GLFWWindow>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class
GLFWWindowTransitPtr GLFWWindowBase::create(void)
{
    GLFWWindowTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopy();

        fc = dynamic_pointer_cast<GLFWWindow>(tmpPtr);
    }

    return fc;
}

GLFWWindow *GLFWWindowBase::createEmptyLocal(BitVector bFlags)
{
    GLFWWindow *returnValue;

    newPtr<GLFWWindow>(returnValue, bFlags);

    returnValue->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

//! create an empty new instance of the class, do not copy the prototype
GLFWWindow *GLFWWindowBase::createEmpty(void)
{
    GLFWWindow *returnValue;

    newPtr<GLFWWindow>(returnValue, Thread::getCurrentLocalFlags());

    returnValue->_pFieldFlags->_bNamespaceMask &=
        ~Thread::getCurrentLocalFlags();

    return returnValue;
}


FieldContainerTransitPtr GLFWWindowBase::shallowCopyLocal(
    BitVector bFlags) const
{
    GLFWWindow *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const GLFWWindow *>(this), bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

FieldContainerTransitPtr GLFWWindowBase::shallowCopyDependent(
    BitVector bFlags) const
{
    GLFWWindow *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const GLFWWindow *>(this), ~bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask = bFlags;

    return returnValue;
}

FieldContainerTransitPtr GLFWWindowBase::shallowCopy(void) const
{
    GLFWWindow *tmpPtr;

    newPtr(tmpPtr,
           dynamic_cast<const GLFWWindow *>(this),
           Thread::getCurrentLocalFlags());

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~Thread::getCurrentLocalFlags();

    FieldContainerTransitPtr returnValue(tmpPtr);

    return returnValue;
}




/*------------------------- constructors ----------------------------------*/

GLFWWindowBase::GLFWWindowBase(void) :
    Inherited(),
    _sfGlfwWindow             (GLFWwindowP(nullptr))
{
}

GLFWWindowBase::GLFWWindowBase(const GLFWWindowBase &source) :
    Inherited(source),
    _sfGlfwWindow             (source._sfGlfwWindow             )
{
}


/*-------------------------- destructors ----------------------------------*/

GLFWWindowBase::~GLFWWindowBase(void)
{
}


GetFieldHandlePtr GLFWWindowBase::getHandleGlfwWindow      (void) const
{
    SFGLFWwindowP::GetHandlePtr returnValue(
        new  SFGLFWwindowP::GetHandle(
             &_sfGlfwWindow,
             this->getType().getFieldDesc(GlfwWindowFieldId),
             const_cast<GLFWWindowBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr GLFWWindowBase::editHandleGlfwWindow     (void)
{
    SFGLFWwindowP::EditHandlePtr returnValue(
        new  SFGLFWwindowP::EditHandle(
             &_sfGlfwWindow,
             this->getType().getFieldDesc(GlfwWindowFieldId),
             this));


    editSField(GlfwWindowFieldMask);

    return returnValue;
}


#ifdef OSG_MT_CPTR_ASPECT
void GLFWWindowBase::execSyncV(      FieldContainer    &oFrom,
                                        ConstFieldMaskArg  whichField,
                                        AspectOffsetStore &oOffsets,
                                        ConstFieldMaskArg  syncMode,
                                  const UInt32             uiSyncInfo)
{
    GLFWWindow *pThis = static_cast<GLFWWindow *>(this);

    pThis->execSync(static_cast<GLFWWindow *>(&oFrom),
                    whichField,
                    oOffsets,
                    syncMode,
                    uiSyncInfo);
}
#endif


#ifdef OSG_MT_CPTR_ASPECT
FieldContainer *GLFWWindowBase::createAspectCopy(
    const FieldContainer *pRefAspect) const
{
    GLFWWindow *returnValue;

    newAspectCopy(returnValue,
                  dynamic_cast<const GLFWWindow *>(pRefAspect),
                  dynamic_cast<const GLFWWindow *>(this));

    return returnValue;
}
#endif

void GLFWWindowBase::resolveLinks(void)
{
    Inherited::resolveLinks();


}


OSG_END_NAMESPACE
