/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: dirk@opensg.org, gerrit.voss@vossg.org, carsten_neumann@gmx.net  *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGGLFWWINDOWFIELDS_H_
#define _OSGGLFWWINDOWFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGWindowGLFWDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE


class GLFWWindow;

OSG_GEN_CONTAINERPTR(GLFWWindow);
/*! \ingroup GrpWindowGLFWFieldTraits
    \ingroup GrpLibOSGWindowGLFW
 */
template <>
struct FieldTraits<GLFWWindow *, nsOSG> :
    public FieldTraitsFCPtrBase<GLFWWindow *, nsOSG>
{
  private:

    static PointerType             _type;

  public:

    typedef FieldTraits<GLFWWindow *, nsOSG>  Self;

    enum  : UInt32              { Convertible = NotConvertible };

    static OSG_WINDOWGLFW_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

};

template<> inline
const Char8 *FieldTraits<GLFWWindow *, nsOSG>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecGLFWWindowPtr"; 
}

template<> inline
const Char8 *FieldTraits<GLFWWindow *, nsOSG>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecGLFWWindowPtr"; 
}

template<> inline
const Char8 *FieldTraits<GLFWWindow *, nsOSG>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakGLFWWindowPtr"; 
}

template<> inline
const Char8 *FieldTraits<GLFWWindow *, nsOSG>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdGLFWWindowPtr"; 
}

template<> inline
const Char8 *FieldTraits<GLFWWindow *, nsOSG>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecGLFWWindowPtr"; 
}

template<> inline
const Char8 *FieldTraits<GLFWWindow *, nsOSG>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecGLFWWindowPtr"; 
}

template<> inline
const Char8 *FieldTraits<GLFWWindow *, nsOSG>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakGLFWWindowPtr"; 
}

template<> inline
const Char8 *FieldTraits<GLFWWindow *, nsOSG>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdGLFWWindowPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpWindowGLFWFieldSFields */
typedef PointerSField<GLFWWindow *,
                      RecordedRefCountPolicy, nsOSG  > SFRecGLFWWindowPtr;
/*! \ingroup GrpWindowGLFWFieldSFields */
typedef PointerSField<GLFWWindow *,
                      UnrecordedRefCountPolicy, nsOSG> SFUnrecGLFWWindowPtr;
/*! \ingroup GrpWindowGLFWFieldSFields */
typedef PointerSField<GLFWWindow *,
                      WeakRefCountPolicy, nsOSG      > SFWeakGLFWWindowPtr;
/*! \ingroup GrpWindowGLFWFieldSFields */
typedef PointerSField<GLFWWindow *,
                      NoRefCountPolicy, nsOSG        > SFUncountedGLFWWindowPtr;


/*! \ingroup GrpWindowGLFWFieldMFields */
typedef PointerMField<GLFWWindow *,
                      RecordedRefCountPolicy, nsOSG  > MFRecGLFWWindowPtr;
/*! \ingroup GrpWindowGLFWFieldMFields */
typedef PointerMField<GLFWWindow *,
                      UnrecordedRefCountPolicy, nsOSG> MFUnrecGLFWWindowPtr;
/*! \ingroup GrpWindowGLFWFieldMFields */
typedef PointerMField<GLFWWindow *,
                      WeakRefCountPolicy, nsOSG      > MFWeakGLFWWindowPtr;
/*! \ingroup GrpWindowGLFWFieldMFields */
typedef PointerMField<GLFWWindow *,
                      NoRefCountPolicy, nsOSG        > MFUncountedGLFWWindowPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpWindowGLFWFieldSFields \ingroup GrpLibOSGWindowGLFW */
struct SFRecGLFWWindowPtr : 
    public PointerSField<GLFWWindow *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpWindowGLFWFieldSFields \ingroup GrpLibOSGWindowGLFW */
struct SFUnrecGLFWWindowPtr : 
    public PointerSField<GLFWWindow *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpWindowGLFWFieldSFields \ingroup GrpLibOSGWindowGLFW */
struct SFWeakGLFWWindowPtr :
    public PointerSField<GLFWWindow *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpWindowGLFWFieldSFields \ingroup GrpLibOSGWindowGLFW */
struct SFUncountedGLFWWindowPtr :
    public PointerSField<GLFWWindow *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpWindowGLFWFieldMFields \ingroup GrpLibOSGWindowGLFW */
struct MFRecGLFWWindowPtr :
    public PointerMField<GLFWWindow *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpWindowGLFWFieldMFields \ingroup GrpLibOSGWindowGLFW */
struct MFUnrecGLFWWindowPtr :
    public PointerMField<GLFWWindow *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpWindowGLFWFieldMFields \ingroup GrpLibOSGWindowGLFW */
struct MFWeakGLFWWindowPtr :
    public PointerMField<GLFWWindow *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpWindowGLFWFieldMFields \ingroup GrpLibOSGWindowGLFW */
struct MFUncountedGLFWWindowPtr :
    public PointerMField<GLFWWindow *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGGLFWWINDOWFIELDS_H_ */
